openapi: "3.0.1"
info:
  title: "photo-app-users-api-cognito-stack"
  version: "1.0"
servers:
- url: "https://fdc8f1cya2.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "Prod"
paths:
  /users:
    post:
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:835819417203:function:photo-app-users-api-cogni-CreateUserHandlerFunctio-vc9Z0A8ocRcM/invocations"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
  /login:
    post:
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:835819417203:function:photo-app-users-api-cogni-LoginUserHandlerFunction-7bElsNVCsIee/invocations"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
  /users/me:
    get:
      parameters:
      - name: "AccessToken"
        in: "header"
        required: true
        schema:
          type: "string"
      security:
      - PhotoAppUsersAPIAutorizer: []
      x-amazon-apigateway-request-validator: "Validate query string parameters and\
        \ headers"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:835819417203:function:photo-app-users-api-cognito-GetUserHandlerFunction-WW2o2axL5A4i/invocations"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
  /confirm:
    post:
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:835819417203:function:photo-app-users-api-cogni-ConfirmUserHandlerFuncti-wpnzDBtw5tlh/invocations"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
  /users/{userName}/add-to-group:
    post:
      parameters:
      - name: "userName"
        in: "path"
        required: true
        schema:
          type: "string"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:835819417203:function:photo-app-users-api-cogni-AddUserToGroupHandlerFun-M5XNYRxyorJw/invocations"
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
components:
  securitySchemes:
    PhotoAppUsersAPIAutorizer:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "cognito_user_pools"
      x-amazon-apigateway-authorizer:
        providerARNs:
        - "arn:aws:cognito-idp:us-east-1:835819417203:userpool/us-east-1_1NNdv1tCz"
        type: "cognito_user_pools"
x-amazon-apigateway-request-validators:
  Validate query string parameters and headers:
    validateRequestParameters: true
    validateRequestBody: false
